# dumbpc — PC-specific Hyprland settings

################
### MONITORS ###
################

monitor=DP-3,1920x1080@300,0x0,1
monitor=HDMI-A-1,1920x1080@60,1920x0,1

workspace = 1, monitor:DP-3
workspace = 2, monitor:HDMI-A-1

#############
### INPUT ###
#############

input {
    touchpad {
        natural_scroll = false
    }
}

###############
### DEVICES ###
###############

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# Bind Wacom tablet pen to main monitor
device {
    name = wacom-intuos-pro-s-pen
    output = DP-3
}

# Disable Wacom tablet touch/finger input
device {
    name = wacom-intuos-pro-s-finger
    enabled = false
}
