$background_color = 070909
$foreground_color = a9acac
$accent_color = 2a517f
$wallpaper = /home/dinozover/Pictures/Wallpapers/2026-02-20_19.59.03.png
# above will be appended colors and path to wallpaper from pywal from my script
source = ~/.config/hypr/host-lock.conf
#$font = Monocraft
$font = Departure Mono

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    # uncomment if want a screenshot of the screen on lock screen
    # path = screenshot
    path = $wallpaper
    blur_passes = 3
}

input-field {
    monitor = $primary_monitor
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgb($background_color) # no fill

    outer_color = rgb($accent_color)
    check_color = rgb($background_color)
    fail_color = rgba(ff5a75ff)

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor = $primary_monitor
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = 0, 220
    halign = center
    valign = center
}

# DATE
label {
    monitor = $primary_monitor
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor = $primary_monitor
    text = $LAYOUT[en,ru]
    font_size = 24
    font_family = $font
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
}
